# Generated by Django 4.2.5 on 2023-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationaId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFront', models.ImageField(upload_to='national_id/')),
                ('imageBack', models.ImageField(upload_to='national_id/')),
            ],
        ),
    ]
