# Generated by Django 4.2.5 on 2023-09-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationaid',
            old_name='imageBack',
            new_name='backImage',
        ),
        migrations.RenameField(
            model_name='nationaid',
            old_name='imageFront',
            new_name='frontImage',
        ),
    ]
