# Generated by Django 4.2.5 on 2023-09-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_imageback_nationaid_backimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationaid',
            name='image',
            field=models.ImageField(default=1, upload_to='national_id/'),
            preserve_default=False,
        ),
    ]
