# Generated by Django 4.2.5 on 2023-09-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0004_alter_cameras_created_at'),
        ('dashboard', '0004_department_other_reason_type_visiortype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visiortype',
            new_name='VisiTortype',
        ),
        migrations.RenameField(
            model_name='visitortype',
            old_name='visior_type',
            new_name='visitor_type',
        ),
    ]
