# Generated by Django 4.2.5 on 2023-11-14 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start_working', models.TimeField(default=datetime.time(8, 0))),
                ('num_hour_working', models.DecimalField(decimal_places=2, default=8, max_digits=10)),
                ('url_extract_data', models.URLField(default='http://24.144.84.0:9090/api/')),
                ('url_image', models.URLField(default='http://24.144.84.0:9090/api/')),
                ('url_extract_data_back', models.URLField(default='http://24.144.84.0:9090/api_back/')),
            ],
        ),
    ]
