# Generated by Django 4.2.5 on 2023-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='url_extract_data_back',
            field=models.URLField(default='http://24.144.84.0:9090/api_back/'),
        ),
        migrations.AddField(
            model_name='config',
            name='url_image',
            field=models.URLField(default='http://24.144.84.0:9090/api/'),
        ),
    ]
