# Generated by Django 4.2.5 on 2023-11-15 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0002_alter_cameras_created_at_alter_persons_created_at_and_more'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nabatshieh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_start_working', models.TimeField(default=datetime.time(8, 0))),
                ('num_hour_working', models.DecimalField(decimal_places=2, default=8, max_digits=10)),
                ('persions', models.ManyToManyField(blank=True, to='app_resources.persons')),
            ],
        ),
    ]
