# Generated by Django 4.2.5 on 2023-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_nabatshieh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('when', models.CharField(choices=[('entry', 'الدخول'), ('exit', 'الخروج')], default='entry', max_length=20)),
            ],
        ),
    ]
