# Generated by Django 4.2.5 on 2023-11-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0006_alter_cameras_created_at_alter_persons_created_at'),
        ('config', '0004_alter_reasons_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_hour_working', models.DecimalField(decimal_places=2, default=8, max_digits=10)),
                ('persions', models.ManyToManyField(blank=True, to='app_resources.persons')),
            ],
        ),
    ]
