# Generated by Django 4.2.5 on 2023-11-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0007_alter_cameras_created_at_alter_persons_created_at'),
        ('config', '0005_addduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasons',
            name='fromm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reasons',
            name='persions',
            field=models.ManyToManyField(blank=True, to='app_resources.persons'),
        ),
        migrations.AddField(
            model_name='reasons',
            name='too',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
