# Generated by Django 4.2.5 on 2023-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_reasons_fromm_reasons_persions_reasons_too'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasons',
            name='num_reason',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
