# Generated by Django 4.2.5 on 2023-12-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0017_alter_cameras_created_at_alter_persons_created_at'),
        ('config', '0008_config_token_access_config_url_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_permissions', to='app_resources.persons')),
                ('for_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_emp_permissions', to='app_resources.persons')),
            ],
        ),
    ]
