# Generated by Django 4.2.5 on 2023-12-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0018_alter_cameras_created_at_alter_persons_created_at'),
        ('config', '0009_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.reasons'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='permission',
            name='for_emp',
        ),
        migrations.AddField(
            model_name='permission',
            name='for_emp',
            field=models.ManyToManyField(to='app_resources.persons'),
        ),
    ]
