# Generated by Django 4.2.5 on 2023-12-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0011_alter_permission_created_by_alter_permission_for_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
