# Generated by Django 4.2.5 on 2023-12-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_alter_permission_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
