# Generated by Django 4.2.5 on 2023-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_permission_is_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='is_accept',
            field=models.BooleanField(null=True),
        ),
    ]
