# Generated by Django 4.2.4 on 2023-08-23 11:53

import app_resources.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('camera_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('connection_string', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 23, 14, 53, 7, 372021))),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_resources.models.get_upload_path)),
                ('id_national_img', models.ImageField(blank=True, null=True, upload_to='persons\\national_id')),
                ('id_national', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(default='unknown', max_length=100)),
                ('created_at', models.DateTimeField()),
                ('allowed_cameras', models.ManyToManyField(blank=True, to='app_resources.cameras')),
            ],
        ),
        migrations.CreateModel(
            name='PersonsDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_resources.cameras')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_resources.persons')),
            ],
        ),
    ]
