# Generated by Django 4.2.5 on 2023-09-24 12:13

import app_resources.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0004_department_other_reason_type_visiortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('camera_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('connection_string', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 24, 15, 13, 5, 99823))),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_resources.models.get_upload_path)),
                ('front_national_img', models.ImageField(blank=True, null=True, upload_to='persons\\national_id')),
                ('back_national_img', models.ImageField(blank=True, null=True, upload_to='persons\\national_id')),
                ('id_national', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(default='unknown', max_length=100)),
                ('created_at', models.DateTimeField()),
                ('allowed_cameras', models.ManyToManyField(blank=True, to='app_resources.cameras')),
                ('nationalID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.nationaid')),
            ],
        ),
        migrations.CreateModel(
            name='PersonsDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('outed_at', models.DateTimeField(blank=True, null=True)),
                ('spend_time', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_resources.cameras')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_resources.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('other', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.other')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_resources.persons')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.reason')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.type')),
                ('visior_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.visiortype')),
            ],
        ),
    ]
