# Generated by Django 4.2.5 on 2023-11-14 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('camera_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('connection_string', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 14, 18, 34, 45, 696639))),
            ],
        ),
        migrations.CreateModel(
            name='ImagesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='persons\\images')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('type_register', models.CharField(default='موظف', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('front_national_img', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('back_national_img', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('id_national', models.CharField(blank=True, max_length=300, null=True)),
                ('job_title', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(default='unknown', max_length=100)),
                ('religion', models.CharField(default='مسلم', max_length=100)),
                ('status_person', models.CharField(default='اعزب', max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 11, 14, 16, 34, 45, 696639, tzinfo=datetime.timezone.utc))),
                ('registration_number', models.IntegerField(blank=True, null=True)),
                ('allowed_cameras', models.ManyToManyField(blank=True, to='app_resources.cameras')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('images', models.ManyToManyField(blank=True, null=True, to='app_resources.imagesperson')),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_resources.information')),
            ],
        ),
        migrations.CreateModel(
            name='PersonsDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('outed_at', models.DateTimeField(blank=True, null=True)),
                ('spend_time', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_resources.cameras')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_resources.persons')),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='empolyee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_resources.persons'),
        ),
        migrations.AddField(
            model_name='information',
            name='other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.other'),
        ),
        migrations.AddField(
            model_name='information',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.reason'),
        ),
        migrations.AddField(
            model_name='information',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.type'),
        ),
        migrations.AddField(
            model_name='information',
            name='visior_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.visitortype'),
        ),
    ]
