# Generated by Django 4.1.6 on 2023-08-27 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 0, 53, 34, 886584)),
        ),
        migrations.AlterField(
            model_name='personsdetect',
            name='outed_at',
            field=models.DateTimeField(),
        ),
    ]
