# Generated by Django 4.2.3 on 2023-08-16 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 20, 0, 48, 213823)),
        ),
    ]
