# Generated by Django 4.2.3 on 2023-08-07 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_resources",
            "0002_alter_cameras_created_at_alter_persons_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameras",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 7, 21, 10, 4, 117471)
            ),
        ),
        migrations.AlterField(
            model_name="persons",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 7, 21, 10, 4, 118468)
            ),
        ),
        migrations.AlterField(
            model_name="personsdetect",
            name="detected_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 7, 21, 10, 4, 119466)
            ),
        ),
    ]
