# Generated by Django 4.1.6 on 2023-08-27 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0002_personsdetect_spend_time_alter_cameras_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 13, 41, 23, 354596)),
        ),
        migrations.AlterField(
            model_name='personsdetect',
            name='spend_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
