# Generated by Django 4.2.5 on 2023-09-24 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0002_persons_job_title_alter_cameras_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='person',
        ),
        migrations.AddField(
            model_name='persons',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_resources.information'),
        ),
        migrations.AddField(
            model_name='persons',
            name='type',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('empolyee', 'Empolyee')], default='visitor', max_length=30),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 17, 16, 5, 659893)),
        ),
    ]
