# Generated by Django 4.2.5 on 2023-09-24 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0003_remove_information_person_persons_info_persons_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 17, 29, 46, 858843)),
        ),
    ]
