# Generated by Django 4.2.5 on 2023-09-10 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0003_alter_cameras_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 11, 29, 56, 696148)),
        ),
    ]
