# Generated by Django 4.2.3 on 2023-07-24 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0003_persons_alter_cameras_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 20, 23, 1, 837089)),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 20, 23, 1, 837089)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='image',
            field=models.ImageField(upload_to='persons/'),
        ),
    ]
