# Generated by Django 4.2.3 on 2023-08-12 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0003_alter_cameras_created_at_alter_persons_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='id_national',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='id_national_img',
            field=models.ImageField(blank=True, null=True, upload_to='persons\\national_id'),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 17, 12, 5, 507605)),
        ),
    ]
