# Generated by Django 4.2.5 on 2023-09-24 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0004_alter_cameras_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='type',
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 17, 52, 40, 406056)),
        ),
    ]
