# Generated by Django 4.2.5 on 2023-11-21 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_reasons_when'),
        ('app_resources', '0004_alter_cameras_created_at_alter_persons_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 0, 36, 41, 761967)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 22, 36, 41, 761967, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='DetectReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=200)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.reasons')),
            ],
        ),
        migrations.AddField(
            model_name='personsdetect',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_resources.detectreason'),
        ),
    ]
