# Generated by Django 4.2.5 on 2023-10-09 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0004_alter_cameras_created_at_alter_persons_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 15, 55, 27, 180739)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 12, 55, 27, 180739, tzinfo=datetime.timezone.utc)),
        ),
    ]
