# Generated by Django 4.2.3 on 2023-07-24 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0004_persons_created_at_alter_cameras_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 20, 30, 42, 254891)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 20, 30, 42, 254891)),
        ),
    ]
