# Generated by Django 4.2.3 on 2023-08-12 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0004_persons_id_national_persons_id_national_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 18, 36, 42, 406636)),
        ),
    ]
