# Generated by Django 4.2.5 on 2023-09-24 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0005_remove_persons_type_alter_cameras_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='type_register',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 18, 2, 51, 164906)),
        ),
    ]
