# Generated by Django 4.2.3 on 2023-08-06 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0005_persons_status_alter_cameras_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsUnknown',
            fields=[
                ('persons_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_resources.persons')),
            ],
            bases=('app_resources.persons',),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 20, 45, 58, 230715)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 20, 45, 58, 230715)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='persons/'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='status',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='PersonsDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(default=datetime.datetime(2023, 8, 6, 20, 45, 58, 230715))),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_resources.cameras')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_resources.persons')),
            ],
        ),
    ]
