# Generated by Django 4.2.3 on 2023-08-15 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0005_persons_address_alter_cameras_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 16, 50, 12, 3717)),
        ),
    ]
