# Generated by Django 4.2.5 on 2023-11-22 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0007_alter_cameras_created_at_alter_persons_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 13, 11, 8, 160275)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 11, 11, 8, 160275, tzinfo=datetime.timezone.utc)),
        ),
    ]
