# Generated by Django 4.2.3 on 2023-08-07 12:46

import app_resources.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0007_alter_cameras_created_at_alter_persons_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='allowed_cameras',
            field=models.ManyToManyField(blank=True, to='app_resources.cameras'),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 15, 46, 2, 713758)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 15, 46, 2, 713758)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_resources.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='personsdetect',
            name='detected_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 15, 46, 2, 713758)),
        ),
    ]
