# Generated by Django 4.2.5 on 2023-10-25 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0008_imagesperson_alter_cameras_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='religion',
            field=models.CharField(default='مسلم', max_length=100),
        ),
        migrations.AddField(
            model_name='persons',
            name='status_person',
            field=models.CharField(default='اعزب', max_length=100),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 18, 17, 35, 449561)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 15, 17, 35, 450555, tzinfo=datetime.timezone.utc)),
        ),
    ]
