# Generated by Django 4.2.5 on 2023-10-23 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0008_imagesperson_alter_cameras_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 15, 44, 35, 811886)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 15, 44, 35, 812549, tzinfo=datetime.timezone.utc)),
        ),
    ]
