# Generated by Django 4.2.5 on 2023-11-22 11:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0008_alter_cameras_created_at_alter_persons_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectreason',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectreason',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 13, 15, 20, 682357)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 11, 15, 20, 695032, tzinfo=datetime.timezone.utc)),
        ),
    ]
