# Generated by Django 4.2.3 on 2023-08-08 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0008_persons_allowed_cameras_alter_cameras_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 14, 22, 47, 556180)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 14, 22, 47, 556180)),
        ),
        migrations.AlterField(
            model_name='personsdetect',
            name='detected_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 14, 22, 47, 556180)),
        ),
    ]
