# Generated by Django 4.2.5 on 2023-11-22 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0009_detectreason_code_detectreason_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 13, 20, 14, 520475)),
        ),
        migrations.AlterField(
            model_name='detectreason',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detectreason',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 11, 20, 14, 520475, tzinfo=datetime.timezone.utc)),
        ),
    ]
