# Generated by Django 4.2.5 on 2023-10-25 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0009_persons_religion_persons_status_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 18, 30, 39, 342760)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='back_national_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 15, 30, 39, 342760, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='front_national_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
