# Generated by Django 4.2.5 on 2023-11-26 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0010_alter_cameras_created_at_alter_detectreason_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 15, 46, 26, 81077, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 15, 46, 26, 81804, tzinfo=datetime.timezone.utc)),
        ),
    ]
