# Generated by Django 4.2.5 on 2023-10-31 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0010_alter_cameras_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 15, 9, 6, 770054)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 13, 9, 6, 771055, tzinfo=datetime.timezone.utc)),
        ),
    ]
