# Generated by Django 4.2.5 on 2023-11-28 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0012_alter_cameras_created_at_alter_persons_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 12, 54, 14, 603962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 12, 54, 14, 604529, tzinfo=datetime.timezone.utc)),
        ),
    ]
