# Generated by Django 4.2.5 on 2023-10-31 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0012_alter_cameras_created_at_alter_persons_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='empolyee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_resources.persons'),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 17, 12, 54, 202301)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 15, 12, 54, 203302, tzinfo=datetime.timezone.utc)),
        ),
    ]
