# Generated by Django 4.2.5 on 2023-12-21 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resources', '0016_persons_mobile_whatsapp_alter_cameras_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 7, 10, 24, 782669, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 7, 10, 24, 783719, tzinfo=datetime.timezone.utc)),
        ),
    ]
