# Generated by Django 4.2.5 on 2023-12-21 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
        ('app_resources', '0020_alter_cameras_created_at_alter_persons_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.branch'),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='persons',
            name='images',
            field=models.ManyToManyField(blank=True, to='app_resources.imagesperson'),
        ),
    ]
