# Generated by Django 4.2.5 on 2023-12-31 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_alter_user_branch'),
        ('app_resources', '0021_persons_branch_alter_cameras_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_branch', to='authentications.branch'),
        ),
    ]
